CREATE DATABASE api_todo;

CREATE USER user_todo;

ALTER USER user_todo WITH ENCRYPTED PASSWORD '1122';

GRANT ALL PRIVILEGES ON DATABASE api_todo TO user_todo;

CREATE TABLE todos (id SERIAL PRIMARY KEY, title VARCHAR, description TEXT, done BOOL);

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PUBLIC TO user_todo;

GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA PUBLIC TO user_todo;
